# Sample compose file
version: "3"
services:
  wiremock:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mydb
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: p@55word
